### ISSUE TITLE
eShareResult only closed?

### ISSUE THREAD

**Issue by loftyy** [voxelbusters/Cross-Platform-Native-Plugins-for-Unity#1]
I'm trying to reward players who share but the return for _result is closed even if the player shares. Is there way to reward players who share?

Thank you !

**Comment by loftyy** [comment]
and I have one more question, for the AskForAReview function, how do I use it ? I have no clue how to use it and show the dialog. Do you have an example for me please? Thanks

**Comment by loftyy** [comment]
Hello????

**Comment by voxelbustersold** [comment]
Hi,
     Sorry for delayed reply. We don't follow github notifications. Instead
you can directly shoot a mail to our support (support@voxelbusters.com)

Coming to tour question, on Android its not possible to find out if the
action is successfully finished or not as we delegate the task to other app
activities.

So only closed state is available.

Thanks,
VB Team.

**Comment by loftyy** [comment]
@voxelbusters  thank you. You have a great plugin. Well made. I have one question though, what is the easiest way to remotely send push notifications to all my users whenever there is an update or any other scenario?

**Comment by voxelbustersold** [comment]
For sending Push notifications you need server setup or any third party
push service such as OneSignal, Tapjoy etc.

If you have some knowledge on server programming, you can give a try
setting up https://gist.github.com/joashp/b2f6c7e24127f2798eb2 and
capturing the device tokens of all your users and trigger a notification
from server with a proper payload.

Once after current release, we will try to include sending remote
notifications to device as a testing option with in editor for ease of
development.

Thanks,
VB Team.

**Comment by loftyy** [comment]
@voxelbusters thanks for the suggestion ! that is what i was exactly looking for and it's working now ! I have a final question, for your free android native plugin, I only use the SHOWTOAST and SHARE Methods. I'm having issues with too many methods when I build, is there a way to delete the other methods in your plugin which I don't use?

**Comment by voxelbustersold** [comment]
Sorry for the delayed response.
We have options to enable and disable the features selectively from NPSettings. That should do the expected job.

Thanks,
VB Team
