### ISSUE TITLE
Bug in androidmanifestgenerator in unity 2018.3

### ISSUE THREAD

**Issue by Thaina** [voxelbusters/Cross-Platform-Native-Plugins-for-Unity#3]
```C#
#if NET_4_6
		if (GetAPICompatibilityLevel()== ApiCompatibilityLevel.NET_4_6)
		{
```

Should become

```C#
#if NET_4_6 || NET_STANDARD_2_0
		var compat  = GetAPICompatibilityLevel();
		if (compat == ApiCompatibilityLevel.NET_4_6 || compat == ApiCompatibilityLevel.NET_Standard_2_0)
		{
```

**Comment by voxelbustersold** [comment]
Thanks for reporting.
We submitted a patch and will be available on Asset Store after the review.
Meanwhile please update [this file](https://drive.google.com/file/d/1e895WLfnI9tDbDKgyFXofQ3yTrSI-x8_/view?usp=sharing) and it should work fine.

Thanks,
VB Team
