### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Thaina** [voxelbusters/Cross-Platform-Native-Plugins-for-Unity#4]
Unity 2019.1.7f1
Android build

> Could not get unknown property 'GradleVersion' for repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

**Comment by hoavdc** [comment]
Same problem

**Comment by manwithsteelnerves** [comment]
Hi,
Please contact our support team on skype. The issue happens if your files are not up to date or you are on an older unity version.
Either ways, we can help you out.

Thanks,
VB Team
