### ISSUE TITLE
com.excelliance.kxqp fatal exception on samsung os 10

### ISSUE THREAD

**Issue by codydjango** [voxelbusters/Cross-Platform-Native-Plugins-for-Unity#5]
Beginning September 10th, Samsung OS 10 only. Fatal crash, suspect it's happening on devices with multiple accounts of our application. Is there a preferred process for reporting bugs? Stacktrace?

**Comment by voxelbustersold** [comment]
We sent you a reply on forum.

**Comment by codydjango** [comment]
FYI com.excelliance.kxqp is malware being injected when a particular user wraps our SDK to run it in some unsupported virtualization environment.

https://www.cs.ucr.edu/~heng/pubs/sacmat2020.pdf
https://www.cs.ucr.edu/~zhiyunq/pub/sigmetrics19_app_virtualization.pdf

**Comment by manwithsteelnerves** [comment]
The error seems to happen with in that class. 
Anything we need to be aware to make it compatible?
